# Generated by Django 5.2.6 on 2025-09-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carName', models.CharField(max_length=20)),
                ('carNum', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('buyerName', models.CharField(max_length=20)),
                ('carYear', models.IntegerField()),
            ],
        ),
    ]
