# Generated by Django 5.2.6 on 2025-09-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ormAppVikash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="carColor",
            field=models.CharField(default="Red", max_length=20),
        ),
    ]
